import React from 'react';
import { ArrowLeft, CheckCircle2, Download, FileText, Printer } from "lucide-react";
import { changesDuringIncident, incident, repository, timeline } from "../data/mockData";

export default function ReportPage({ onBack }) {
  return (
    <div className="page-content report-page">
      <div className="report-toolbar">
        <button className="back-button" onClick={onBack}>
          <ArrowLeft size={16} /> Back to incident
        </button>
        <div className="report-toolbar-actions">
          <button className="secondary-button"><Printer size={16} /> Print</button>
          <button className="primary-button"><Download size={16} /> Download report</button>
        </div>
      </div>

      <article className="report-document">
        <header className="report-cover">
          <div className="report-brand">
            <div className="brand-mark"><FileText size={20} /></div>
            <strong>RootLens AI</strong>
          </div>
          <span className="report-type">INCIDENT REPORT</span>
          <h1>{incident.title}</h1>
          <p>{incident.id} · {incident.detectedAt}</p>
        </header>

        <section className="report-section report-overview">
          <div className="report-stat">
            <span>Severity</span>
            <strong className="danger-text">{incident.severity}</strong>
          </div>
          <div className="report-stat">
            <span>AI confidence</span>
            <strong>{incident.confidence}%</strong>
          </div>
          <div className="report-stat">
            <span>Repository</span>
            <strong>{repository.name}</strong>
          </div>
          <div className="report-stat">
            <span>Branch</span>
            <strong>{repository.branch}</strong>
          </div>
        </section>

        <ReportSection title="1. Executive summary">
          <p>
            RootLens identified a probable relationship between the incident
            and a recent payment API refactoring. The investigation correlates
            the stack trace with files changed shortly before the incident and
            records the subsequent recovery changes.
          </p>
        </ReportSection>

        <ReportSection title="2. Detected error">
          <div className="report-code">{incident.error}</div>
        </ReportSection>

        <ReportSection title="3. Probable root cause">
          <p>{incident.rootCause}</p>
        </ReportSection>

        <ReportSection title="4. Likely triggering change">
          <div className="report-commit">
            <GitCommitIcon />
            <div>
              <strong>{incident.likelyCommit.message}</strong>
              <span>{incident.likelyCommit.hash} · {incident.likelyCommit.author}</span>
            </div>
          </div>
          <ul className="report-list">
            {incident.evidence.map((item) => <li key={item}>{item}</li>)}
          </ul>
        </ReportSection>

        <ReportSection title="5. Changes made during the incident">
          <table className="report-table">
            <thead>
              <tr><th>Time</th><th>Developer</th><th>Commit</th><th>Change</th></tr>
            </thead>
            <tbody>
              {changesDuringIncident.map((change) => (
                <tr key={change.commit}>
                  <td>{change.time}</td>
                  <td>{change.author}</td>
                  <td className="mono">{change.commit}</td>
                  <td>{change.change}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </ReportSection>

        <ReportSection title="6. Incident timeline">
          <div className="report-timeline">
            {timeline.map((event) => (
              <div className="report-timeline-row" key={event.time}>
                <span>{event.time}</span>
                <strong>{event.title}</strong>
                <p>{event.description}</p>
              </div>
            ))}
          </div>
        </ReportSection>

        <ReportSection title="7. Affected components">
          <div className="report-files">
            {incident.affectedFiles.map((file) => <span key={file}>{file}</span>)}
          </div>
        </ReportSection>

        <ReportSection title="8. Recommended resolution">
          <div className="recommendation-box">
            <CheckCircle2 size={18} />
            <p>{incident.suggestedFix}</p>
          </div>
        </ReportSection>

        <ReportSection title="9. Prevention">
          <p>{incident.prevention}</p>
        </ReportSection>

        <footer className="report-footer">
          <span>Generated by RootLens AI</span>
          <span>Evidence-based AI assistance · Verify before production action</span>
        </footer>
      </article>
    </div>
  );
}

function ReportSection({ title, children }) {
  return (
    <section className="report-section">
      <h2>{title}</h2>
      {children}
    </section>
  );
}

function GitCommitIcon() {
  return <div className="report-commit-icon">↳</div>;
}
